# instance for template metric
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: instance-appid-api
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      properties:
        authorization_header:  request.headers["authorization"]
        #destination_ip: destination.ip | ip("0.0.0.0")
        destination_service_host: destination.service.host | ""