apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Chart.Name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: multi-cloud-identity-and-access-policy-manager
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
  selector:
    app: multi-cloud-identity-and-access-policy-manager
