apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: rule-hello-world-backend
  namespace: istio-system
spec:
  actions:
  - handler: handler-appid-api.istio-system
    instances:
    - instance-appid-api
  match: destination.service.host == "svc-hello-world-backend.multi-cloud-tech-preview.svc.cluster.local"
