apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dpl-{{ .Chart.Name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: multi-cloud-identity-and-access-policy-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: multi-cloud-identity-and-access-policy-manager
    spec:
      containers:
      - name: multi-cloud-identity-and-access-policy-manager
        image: ibmcloudsecurity/multi-cloud-tech-preview-multi-cloud-manager:latest
        ports:
        - containerPort: 3001
        env:
         - name: TENANT_ID
           valueFrom:
             configMapKeyRef:
               name: cfgmap-{{ .Chart.Name }}-{{ .Release.Name }}
               key: tenant_id
         - name: CLIENT_ID
           valueFrom:
             configMapKeyRef:
               name: cfgmap-{{ .Chart.Name }}-{{ .Release.Name }}
               key: client_id
         - name: SECRET
           valueFrom:
             configMapKeyRef:
               name: cfgmap-{{ .Chart.Name }}-{{ .Release.Name }}
               key: secret
         - name: APPID_URL
           valueFrom:
             configMapKeyRef:
               name: cfgmap-{{ .Chart.Name }}-{{ .Release.Name }}
               key: appid_url

