apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-hello-world-frontend
  namespace: multi-cloud-tech-preview
data:
  tenant_id: "<App ID tenant id>"
  client_id: "<App ID client id>"
  secret: "<App ID secret>"
  appid_url: "<App ID oauth server url>"
  backend_url: "<Public URL to your backend application>"
  public_web_url: "<Public URL to the frontend application>"