apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dpl-hello-world-frontend
  namespace: multi-cloud-tech-preview
  labels:
    app: hello-world-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-frontend
    spec:
      containers:
      - name: hello-world-frontend
        image: ibmcloudsecurity/multi-cloud-tech-preview-hello-world-frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: backend_url
            valueFrom:
              configMapKeyRef:
                name: cfgmap-hello-world-frontend
                key: backend_url
          - name: public_web_url
            valueFrom:
              configMapKeyRef:
                name: cfgmap-hello-world-frontend
                key: public_web_url
          - name: TENANT_ID
            valueFrom:
              configMapKeyRef:
                name: cfgmap-hello-world-frontend
                key: tenant_id
          - name: CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: cfgmap-hello-world-frontend
                key: client_id
          - name: SECRET
            valueFrom:
              configMapKeyRef:
                name: cfgmap-hello-world-frontend
                key: secret
          - name: APPID_URL
            valueFrom:
              configMapKeyRef:
                name: cfgmap-hello-world-frontend
                key: appid_url